AdminBanHoa/AdminBanHoa/AdminBanHoa/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminBanHoa.Models;

namespace AdminBanHoa.Controllers
{
    public class SanPhamController : Controller
    {
        DBBANHOADataContext db = new DBBANHOADataContext();
        //
        // GET: /SanPham/
        public ActionResult SanPhamPartial()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View(db.SanPhams.ToList());
        }
        public ActionResult Details(string id)
        {
            if (String.IsNullOrEmpty(id))
                return RedirectToAction("Index");
            return View(db.SanPhams.FirstOrDefault(t => t.MaSP == id));
        }
        public ActionResult Edit(string id)
        {
            if (String.IsNullOrEmpty(id))
                return RedirectToAction("Index");
            var items = db.LoaiSanPhams.ToList();
            if( items != null)
            {
                ViewBag.data = items;
            }
            return View(db.SanPhams.FirstOrDefault(t => t.MaSP == id));
        }
        private string SaveImage(HttpPostedFileBase file)
        {
            // Tạo đường dẫn lưu trữ hình ảnh

            string imagePath = file.FileName;

            // Trả về đường dẫn hình ảnh
            return imagePath;
        }
        [HttpPost]
        public ActionResult Edit(SanPham sp, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                SanPham model = db.SanPhams.Where(t => t.MaSP.Equals(sp.MaSP)).FirstOrDefault();

                // Lấy thông tin hình ảnh cũ
                string oldImagePath = model.HinhAnh;

                // Kiểm tra xem người dùng có tải lên hình ảnh mới hay không
                if (Request.Files.Count > 0)
                {
                    // Lưu hình ảnh mới vào thư mục lưu trữ hình ảnh
                    string newImagePath = SaveImage(Request.Files["HinhAnh"]);

                   

                    // Cập nhật thông tin hình ảnh mới vào cơ sở dữ liệu
                    model.HinhAnh = newImagePath;

                    if (String.IsNullOrEmpty(newImagePath))
                        model.HinhAnh = oldImagePath;
                }

                string MaLoaiSP = Request.Form["TenLoaiSP"].ToString();

                model.TenNCC = sp.TenNCC;
                model.TenSP = sp.TenSP;
                model.MauSP = sp.MauSP;
                model.Gia = sp.Gia;
                model.MoTa = sp.MoTa;

                model.MaLoaiSP = MaLoaiSP;

                //model.HinhAnh = sp.HinhAnh;

                model.SoLuongTonKho = sp.SoLuongTonKho;

                if (sp.SoLuongTonKho > 0)
                    model.TinhTrang = "Còn hàng";
                else
                    model.TinhTrang = "Hết hàng";
                //db.SanPhams.InsertOnSubmit(sp);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
            return View(sp);
        }

        public ActionResult Create()
        {
            var data = db.LoaiSanPhams.ToList();
            List<SelectListItem> lstLoaiHoa = new List<SelectListItem>();
            foreach (var item in data)
            {
                lstLoaiHoa.Add(new SelectListItem { Text = item.TenLoaiSP, Value = item.MaLoaiSP.ToString() });
            }
            ViewBag.MaLoaiSP = lstLoaiHoa;
            return View();
            //var data = db.LoaiSanPhams.ToList();
            //ViewBag.MaLoaiSP = new SelectList(data, dataValueField: "MaLoaiSP", dataTextField: "TenLoaiSP");
            //return View();
        }

        [HttpPost]
        public ActionResult Create(SanPham sp)
        {

            if(ModelState.IsValid)
            {
                

                var MaSP = Request.Form["MaSP"].ToString();
                var MaLoaiSP = Request.Form["MaLoaiSP"].ToString();
                var TenNCC = Request.Form["TenNCC"].ToString();
                var TenSP = Request.Form["TenSP"].ToString();
                var MauSP = Request.Form["MauSP"].ToString();
                var Gia = Request.Form["Gia"];
                var MoTa = Request.Form["MoTa"].ToString();
                
                var SoLuongTonKho = Request.Form["SoLuongTonKho"];

                string newImagePath = SaveImage(Request.Files["HinhAnh"]);

                var check = db.SanPhams.FirstOrDefault(t => t.MaSP == MaSP);
                if (check != null)
                {
                    Session["AddError"] = "Thêm thất bại";
                    return RedirectToAction("Index");
                }
                else
                {
                    sp.MaSP = MaSP;
                    sp.TenSP = TenSP;
                    sp.MaLoaiSP = MaLoaiSP;
                    sp.MauSP = MauSP;
                    sp.Gia = double.Parse(Gia);
                    sp.MoTa = MoTa;
                    sp.HinhAnh = newImagePath;
                    sp.SoLuongTonKho = int.Parse(SoLuongTonKho);
                    if (sp.SoLuongTonKho > 0)
                        sp.TinhTrang = "Còn Hàng";

                    db.SanPhams.InsertOnSubmit(sp);
                    db.SubmitChanges();
                    return RedirectToAction("Index");
                }

            }
            return View();
        }
	}
}

AdminBanHoa/AdminBanHoa/AdminBanHoa/Views/SanPham/Create.cshtml
@model AdminBanHoa.Models.SanPham

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h2>Thêm Sản Phẩm</h2>
<p style="padding-left:20px;padding-top:20px;">
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</p>
<div class="background-dsdonhang">
    <div class="content1">
        <div class="dsdonhang">
            @using (Html.BeginForm("Create", "SanPham", System.Web.Mvc.FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    @Html.ValidationSummary(true)

                    <div class="form-group">
                        <div class="control-label col-md-2">Mã Sản Phẩm</div>
                        <div class="col-md-10">
                            <input name="MaSP" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Tên Loại Sản Phẩm</div>
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.MaLoaiSP)
                                @Html.ValidationMessageFor(model => model.MaLoaiSP)*@
                            @Html.DropDownListFor(model => model.MaLoaiSP, (IEnumerable<SelectListItem>)ViewBag.MaLoaiSP, new { @class = "form-control" })
                            @*@Html.DropDownList(name: "MaLoaiSP", selectList: null, htmlAttributes: new { @class = "form-control"})*@
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Tên Nhà Cung Cấp</div>
                        <div class="col-md-10">
                            <input name="TenNCC" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Tên Sản Phẩm</div>
                        <div class="col-md-10">
                            <input name="TenSP" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Màu Sắc</div>
                        <div class="col-md-10">
                            <input name="MauSP" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Giá</div>
                        <div class="col-md-10">
                            <input type="number" name="Gia" min="1" required />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Mô Tả</div>
                        <div class="col-md-10">
                            <input name="MoTa" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Hình Ảnh</div>
                        <div class="col-md-10">
                            <input class="form-control" type="file" name="HinhAnh" id="formFile" accept="image/png, image/jpeg" required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Số Lượng Tồn Kho</div>
                        <div class="col-md-10">
                            <input type="number" name="SoLuongTonKho" min="0" required />

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Thêm" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }


        </div>
    </div>

</div>

AdminBanHoa/AdminBanHoa/AdminBanHoa/Views/SanPham/Details.cshtml
@model AdminBanHoa.Models.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h1>CHI TIẾT HOA</h1>
<p style="padding-left:20px;padding-top:20px;">
    @Html.ActionLink("Quay lại ", "Index", null, new { @class = "btn btn-primary" })
    @Html.ActionLink("Sửa", "Edit", new { id = Model.MaSP }, new { @class = "btn btn-primary" })

</p>
<div class="background-dsdonhang">
    <div class="content1">
        <div class="dsdonhang">
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        Mã Sản Phẩm
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MaSP)
                    </dd>

                    <dt>
                        Tên Loại Sản Phẩm
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.LoaiSanPham.TenLoaiSP)
                    </dd>

                    <dt>
                        Tên Nhà Cung Cấp
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenNCC)
                    </dd>

                    <dt>
                        Tên Sản Phẩm
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TenSP)
                    </dd>

                    <dt>
                        Màu Sắc
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MauSP)
                    </dd>

                    <dt>
                        Giá
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Gia).000 VND
                    </dd>

                    <dt>
                        Mô Tả
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MoTa)
                    </dd>

                    <dt>
                        Hình Ảnh
                    </dt>

                    <dd>
                        <img style="width:300px" src="@Url.Content("/Content/img/"+Model.HinhAnh)"/>
                    </dd>

                    <dt>
                        Số Lượng Tồn Kho
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.SoLuongTonKho)
                    </dd>

                    <dt>
                        Tình Trạng
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.TinhTrang)
                    </dd>

                </dl>
            </div>

        </div>
    </div>

</div>

AdminBanHoa/AdminBanHoa/AdminBanHoa/Views/SanPham/Edit.cshtml
@model AdminBanHoa.Models.SanPham

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<p style="padding-left:30px;padding-top:20px;">
    <h2>Chỉnh Sửa</h2>
</p>
<div>
    @Html.ActionLink("Quay lại", "Index", null, new { @class = "btn btn-primary" })
</div>
<div class="background-dsdonhang">
    <div class="content1">
        <div class="dsdonhang">
            @using (Html.BeginForm("Edit", "SanPham", System.Web.Mvc.FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4 style="text-align: center; display: flex; align-items: center; justify-content: center; ">Sản phẩm</h4>
                    <hr />
                    @Html.ValidationSummary(true)
                    @Html.HiddenFor(model => model.MaSP)

                    <div class="form-group">
                        <div class="control-label col-md-2">Tên Loại Sản Phẩm</div>
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.MaLoaiSP)
                                @Html.ValidationMessageFor(model => model.MaLoaiSP)*@
                            @Html.DropDownList("TenLoaiSP", new SelectList(ViewBag.data, "MaLoaiSP", "TenLoaiSP"))
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Tên Nhà Cung Cấp</div>
                        <div class="col-md-10">
                            <input value="@Model.TenNCC" name="TenNCC" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Tên Sản Phẩm</div>
                        <div class="col-md-10">
                            <input value="@Model.TenSP" name="TenSP" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Màu Sắc</div>
                        <div class="col-md-10">
                            <input value="@Model.MauSP" name="MauSP" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Giá</div>
                        <div class="col-md-10">
                            <input type="number" name="Gia" min="1" required value="@Model.Gia" />

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Mô Tả</div>
                        <div class="col-md-10">
                            
                            <input value="@Model.MoTa" name="MoTa" required type="text" />
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Hình Ảnh</div>
                        <div class="col-md-10">
                            <input class="form-control" type="file" name="HinhAnh" id="formFile" accept="image/png, image/jpeg">


                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Số Lượng Tồn Kho</div>
                        <div class="col-md-10">
                            <input type="number" name="SoLuongTonKho" required min="0" value="@Model.SoLuongTonKho" />

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="control-label col-md-2">Tình Trạng</div>
                        <div class="col-md-10">
                            <input value="@Model.TinhTrang" disabled="disabled" />

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lưu" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>

</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#TenLoaiSP").val('@Model.MaLoaiSP')
    })
</script>

AdminBanHoa/AdminBanHoa/AdminBanHoa/Views/SanPham/Index.cshtml
@model IEnumerable<AdminBanHoa.Models.SanPham>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<div class="tieude">
    <h1 style="text-align:center">DANH SÁCH SẢN PHẨM</h1>
</div>
<p style="padding-left:20px;padding-top:20px;">
    @Html.ActionLink("Thêm Sản Phẩm Mới", "Create", null, new { @class = "btn btn-primary" })
</p>
@if (Session["AddError"] != null)
{
    <p class="text-danger">@Session["AddError"]</p>
    Session["AddError"] = null;
}

<div class="background-dsdonhang">
    <div class="content1">
        <div class="dsdonhang">
            <table class="table">
                <tr>
                    <th>
                        Mã Sản Phẩm
                    </th>
                    <th>
                        Tên Sản Phẩm
                    <th>
                        Màu Sắc
                    </th>
                    <th>
                        Giá
                    </th>
                    <th>
                        Mô Tả
                    </th>
                    <th>
                        Hình Ảnh
                    </th>
                    <th>
                        Số Lượng Tồn Kho
                    </th>
                    <th>
                        Tình Trạng
                    </th>
                    <th>
                        Tên Nhà Cung Cấp
                    </th>
                    <th>
                        Loại Sản Phẩm
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.MaSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MauSP)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Gia)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.MoTa)
                        </td>
                        <td>
                            <img style="width:50px;" src="@Url.Content("/Content/img/" + item.HinhAnh)" />
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SoLuongTonKho)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TinhTrang)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TenNCC)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LoaiSanPham.TenLoaiSP)
                        </td>
                        <td>
                            @Html.ActionLink("Sửa", "Edit", new { id = item.MaSP }, new { @class = "btn btn-primary" })
                        </td>
                        <td>
                            @Html.ActionLink("Chi tiết", "Details", new { id = item.MaSP }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>

</div>

AdminBanHoa/AdminBanHoa/AdminBanHoa/Views/SanPham/SanPhamPartial.cshtml
<a href="@Url.Action("Index","SanPham")">

    <p>Sản Phẩm</p>

</a>