AdminBanHoa/AdminBanHoa/AdminBanHoa/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminBanHoa.Models;

namespace AdminBanHoa.Controllers
{
    public class DonHangController : Controller
    {
        DBBANHOADataContext db = new DBBANHOADataContext();
        DonHangAPIController APIDonHang = new DonHangAPIController();
        //
        // GET: /DonHang/
        public ActionResult DonHangPartial()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View(db.DonHangs.ToList());
        }
        public ActionResult Edit(string id)
        {
            if (String.IsNullOrEmpty(id))
                return RedirectToAction("Index");
            return View(db.DonHangs.FirstOrDefault(t =>t.MaDH == id));
        }

        [HttpPost]
        public ActionResult Edit(DonHang dh)
        {
            //DonHang model = db.DonHangs.FirstOrDefault(t => t.MaDH == dh.MaDH);

            //if (dh.NgayGiaoHoa < DateTime.Now || dh.NgayGiaoHoa < dh.NgayDatHoa)
            //    return View(model);
            //model.NgayGiaoHoa = dh.NgayGiaoHoa;
            //if (String.IsNullOrEmpty(dh.TinhTrangDH))
            //    model.TinhTrangDH = "Đang Chờ Xử Lí";
            //else
            //    model.TinhTrangDH = dh.TinhTrangDH;

            //db.SubmitChanges();

            //return RedirectToAction("Index");

            bool check = APIDonHang.Update(dh.MaDH, dh.NgayGiaoHoa, dh.TinhTrangDH);
            if (check == true)
                return RedirectToAction("Index");
            else
                return View();
        }

        public ActionResult Details(string id)
        {
            if (String.IsNullOrEmpty(id))
                return RedirectToAction("Index");
            var JoinTable = db.CTDonHangs
                                .Join(db.SanPhams, ct => ct.MaSP, sp => sp.MaSP, (ct, sp) => new { ct, sp })
                                .Select(m => new ChiTietDH
                                {
                                    MaDH = m.ct.MaDH,
                                    MaSP = m.ct.MaSP,
                                    TenSP = m.sp.TenSP,
                                    HinhAnh = m.sp.HinhAnh,
                                    SL = m.ct.SL,
                                    ThanhTien = m.ct.ThanhTien
                                });
            var chiTiet = JoinTable.Where(j => j.MaDH == id);
            return View(chiTiet);
        }
        public ActionResult DetailsSP(string id)
        {
            return this.RedirectToAction("Details", "SanPham", new { id = id });
        }
	}
}

AdminBanHoa/AdminBanHoa/AdminBanHoa/Controllers/KhachHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminBanHoa.Models;
namespace AdminBanHoa.Controllers
{
    public class KhachHangController : Controller
    {
        DBBANHOADataContext db = new DBBANHOADataContext();
        //
        // GET: /KhachHang/
        public ActionResult KhachHangPartial()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View(db.KhachHangs.ToList());
        }
	}
}

AdminBanHoa/AdminBanHoa/AdminBanHoa/Controllers/LoaiSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdminBanHoa.Models;
namespace AdminBanHoa.Controllers
{
    public class LoaiSanPhamController : Controller
    {
        DBBANHOADataContext db = new DBBANHOADataContext();
        //
        // GET: /LoaiSanPham/
        public ActionResult LoaiSanPhamPartial()
        {
            return View();
        }

        public ActionResult Index()
        {
            return View(db.LoaiSanPhams.ToList());
        }


        [HttpPost]
        public JsonResult Add(LoaiSanPham f)
        {   
            int kq = 1;
            try
            {
                db.LoaiSanPhams.InsertOnSubmit(f);
                db.SubmitChanges();
            }
            catch
            {
                kq = 0;
            }
            return Json(kq, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Edit(string id)
        {
            if (String.IsNullOrEmpty(id))
                return RedirectToAction("Index");
            return View(db.LoaiSanPhams.FirstOrDefault(t => t.MaLoaiSP == id));
        }

        [HttpPost]
        public ActionResult Edit(LoaiSanPham l)
        {
            LoaiSanPham model = db.LoaiSanPhams.FirstOrDefault(t => t.MaLoaiSP == l.MaLoaiSP);

            model.TenLoaiSP = l.TenLoaiSP;

            db.SubmitChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id)
        {
            if (String.IsNullOrEmpty(id))
                return RedirectToAction("Index");
            return View(db.LoaiSanPhams.FirstOrDefault(t => t.MaLoaiSP == id));
        }

        [HttpPost]
        public ActionResult Delete(string id, string temp)
        {
            var check = db.SanPhams.Where(t => t.MaLoaiSP == id).ToList();
            if (check.Count > 0)
            {
                Session["DeleteError"] = "Xoá Thất Bại";
                return RedirectToAction("Index");
                
            }
            else
            {
                LoaiSanPham l = db.LoaiSanPhams.FirstOrDefault(t => t.MaLoaiSP == id);
                db.LoaiSanPhams.DeleteOnSubmit(l);
                db.SubmitChanges();
                return RedirectToAction("Index");
            }
        }
	}
}

AdminBanHoa/AdminBanHoa/AdminBanHoa/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i">
    <link rel="stylesheet" href="@Url.Content("/Content/css/ready.css")">
    <link rel="stylesheet" href="@Url.Content("/Content/css/demo.css")">
    <link rel="stylesheet" href="~/Content/css/layoutmain.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <script src="@Url.Content("/Content/js/Ajax.js")"></script>

    <title>@Page.Title</title>
    @RenderSection("head", required: false)
</head>
<body>
    <div class="wrapper">
        <div class="main-header" style="height:50px">
            <div class="logo-header">
                <a href="#" class="logo">
                   TheFlower
                </a>
                <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-controls="sidebar" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <button class="topbar-toggler more"><i class="la la-ellipsis-v"></i></button>
            </div>
        </div>

        <div class="sidebar">
         
            <div class="scrollbar-inner sidebar-wrapper">

                <ul class="nav">
                    <li class="nav-item">
                        @Html.Action("SanPhamPartial", "SanPham")
                    </li>
                    <li class="nav-item">
                        @Html.Action("LoaiSanPhamPartial", "LoaiSanPham")
                    </li>
                    <li class="nav-item">
                        @Html.Action("KhachHangPartial", "KhachHang")
                    </li>
                    <li class="nav-item">
                        @Html.Action("DonHangPartial", "DonHang")
                    </li>
                </ul>
            </div>
        </div>
      
        <div class="main-panel">
            <div class="content">
                <div style="height:10px"></div>
                <div class="container-fluid">
                    <h4 class="page-title">@RenderBody()</h4>
                </div>
            </div>
        </div>
    </div>
    
</body>

</html>