WebBanHoa/WebBanHoa/BanHoa/Controllers/LoaiHoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BanHoa.Models;

namespace BanHoa.Controllers
{
    public class LoaiHoaController : Controller
    {
        DBBANHOADataContext db = new DBBANHOADataContext();
        //
        // GET: /LoaiHoa/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult LoaiHoaPartial()
        {
            var lstLoai = db.LoaiSanPhams.OrderBy(t => t.TenLoaiSP).ToList();
            return View(lstLoai);
        }
        public ActionResult LoaiHoaTheoMa(string MaLH)
        {
            
            var list = db.SanPhams.Where(t => t.MaLoaiSP == MaLH && t.SoLuongTonKho >0).ToList();
            if (list.Count == 0)
            {
                ViewBag.Loai = "Không tồn tại hoa theo loài hoa này!";
            }
            return View(list);
        }
	}
}

WebBanHoa/WebBanHoa/BanHoa/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BanHoa.Models;
using System.IO;

namespace BanHoa.Controllers
{
    public class ProductController : Controller
    {
        DBBANHOADataContext db = new DBBANHOADataContext();
        //
        // GET: /Product/
        public ActionResult Products()
        {
            var listProduct = db.SanPhams.Where(t => t.SoLuongTonKho > 0).ToList();
            return View(listProduct);
        }
        public ActionResult Details(string id = "")
        {
            if (String.IsNullOrEmpty(id))
                return RedirectToAction("Products");
            var query = from u in db.SanPhams
                        where u.MaSP.Equals(id)
                        select u;
                        

            var SP = query.AsEnumerable().Select(u =>
                         new SanPham
                         {
                             MaSP = u.MaSP,
                             //MaSP, MaLoaiSP, TenNCC, TenSP, MauSP, Gia, MoTa, HinhAnh, SoLuongTonKho, TinhTrang
                             MaLoaiSP = u.MaLoaiSP,
                             TenNCC = u.TenNCC,
                             TenSP = u.TenSP,
                             MauSP = u.MauSP,
                             Gia = u.Gia,
                             MoTa = u.MoTa,
                             HinhAnh = u.HinhAnh,
                             SoLuongTonKho = u.SoLuongTonKho,
                             TinhTrang = u.TinhTrang
                         }).FirstOrDefault();
            return View(SP);
        }
	}
}

WebBanHoa/WebBanHoa/BanHoa/Views/Product/Details.cshtml
@model BanHoa.Models.SanPham

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}

<div style="height:130px"></div>
<div class="background-chitietsp">
    <div class="row ">
        <div class="col-4 ">
            <div class="imgCTSP">
                <img class="imgSP" src="@Url.Content("/Content/img/" + Model.HinhAnh)" />
            </div>

        </div>

        <div class="col">
            <div class="inf-ctSP">
                <h2>Thông Tin Sản Phẩm</h2>
                <div class="gachngang" style="background-color: #CCCCCC;"></div>
                <p class="ttctSP">
                    @Html.DisplayFor(model => model.TenNCC)
                </p>

                <p class="ttctSP">
                    <h2>@Html.DisplayFor(model => model.TenSP)</h2>
                </p>
                <p class="ttctSP1">
                    <h1 style="color: #EB2727 ; font-size:30pt; "><span style="text-decoration: underline; color: #EB2727; font-size: 15pt; vertical-align: super; ">đ</span>@Html.DisplayFor(model => model.Gia).000</h1>
                </p>
                <table>
                    <tr class="khoangcachttsp">
                        <td>Màu sắc :</td>
                        <td>

                            @Html.DisplayFor(model => model.MauSP)

                        </td>
                    </tr>
                    <tr></tr>
                    <tr class="khoangcachttsp">
                        <td>Mô tả :</td>
                        <td>

                            @Html.DisplayFor(model => model.MoTa)

                        </td>
                    </tr>
                    <tr class="khoangcachttsp">
                        <td>Số lượng hàng còn  :</td>
                        <td>

                            @Html.DisplayFor(model => model.SoLuongTonKho)

                        </td>
                    </tr>
                    <tr class="khoangcachttsp">
                        <td>Tình trạng :</td>
                        <td>

                            @Html.DisplayFor(model => model.TinhTrang)

                        </td>
                    </tr>
                </table>




                <div class="soluong">
                    @using (Html.BeginForm("ThemGioHang", "Cart", new { mh = Model.MaSP, @strURL = Request.Url.ToString() }, FormMethod.Post))
                    {
                        <input type="number" min="1" value="1" name="SoLuong" max="@Model.SoLuongTonKho" />
                        <input type="submit" value="Thêm vào giỏ hàng" class="btn btn-primary" />

                    }
                </div>
               
            </div>

        </div>
    </div>
</div>

    

WebBanHoa/WebBanHoa/BanHoa/Views/Product/Products.cshtml
@model IEnumerable<BanHoa.Models.SanPham>

@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_LayoutPage1.cshtml";
}
!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Sản phẩm</title>
</head>s
<body>
    <div style="height:90px"></div>
    <div class="background-products">
        <div class="row align-items-start d-flex">
            <div class="col-2" >
                <div class="menu-loaihoa">  
                    <div class="menu-child-loaihoa">
                        @Html.Action("LoaiHoaPartial", "LoaiHoa")
                    </div>
                   
                </div>  
            </div>

            <div class="col">
                <div class="Product-card-container">
                    <div class="Product-card">
                        <div class="CHUDE" style="text-align:center;">

                            <h3>Tất cả danh mục sản phẩm </h3>
                            <div style="height:10px;"></div>
                        </div>
                        @ViewBag.Loai
                        @foreach (var item in Model)
                        {

                            @*--------------------------- HÀNG SẢN PHẨM ---------------------------*@

                            <div justify-content-center" style="float: left; justify-content: center; align-items: center; padding-left: 2%; padding-bottom: 2%;">
                                <div class="card" onclick="redirectToDetailsPage('@item.MaSP')">
                                    <div class="img-anhSP">
                                        <img src="@Url.Content("/Content/img/" + item.HinhAnh)" class="card-img-top" alt="...">
                                    </div>

                                    <div class="card-body">
                                        @if (item.TenSP.Count() > 17)
                                        {
                                            <p class="card-title" style="color: black; font-size: 12pt;">@(item.TenSP.Substring(0, 17) + "...")</p>
                                        }
                                        else
                                        {
                                            <p class="card-title" style="color: black; font-size: 12pt;">@Html.DisplayFor(modelItem => item.TenSP)</p>
                                        }
                                        <p class="card-text" style="color: black;">
                                            màu sắc : @Html.DisplayFor(modelItem => item.MauSP)
                                        </p>
                                        <h3 class="Gia" style="color: #EB2727; "><span style="text-decoration: underline; color: #EB2727; font-size: 15pt; vertical-align: super; ">đ</span>@Html.DisplayFor(modelItem => item.Gia).000</h3>

                                    </div>
                                </div>

                            </div>
                        }
                    </div>

                </div>

            </div>
        </div>
    </div>
</body>

</html>
<script>
    function redirectToDetailsPage(id) {
        // Thực hiện chuyển hướng đến trang chi tiết khi click vào card
        window.location.href = '@Url.Action("Details", "Product")/' + id;
    }
</script>